services:
  server:
    build: 
      context: .
      target: python
    working_dir: /app
    command: python -m server.tls_claude
    volumes:
      - ./server:/app/server
    environment:
      - HOST=0.0.0.0
      - PORT=8000
  client:
    build:
      context: .
      target: python
    working_dir: /app
    command: python client.py
    volumes:
      - ./client:/app
    environment:
      - HOST=server
      - PORT=8000
    depends_on:
      - server
  rust_client:
    build:
      context: ./rust_client
      dockerfile: ../Dockerfile
      target: rust
    environment:
      - HOST=server
      - PORT=8000
  receiver:
    build: 
      context: .
      target: receiver
    environment:
      - HOST=0.0.0.0
      - PORT=9003
    ports:
      - "9003:9003/tcp"
  go_receiver:
    build:
      context: .
      target: go_receiver
    environment:
      - HOST=0.0.0.0
      - PORT=9003
    ports:
      - "9003:9003/tcp"
    volumes:
      - ./certs:/certs
