services:
  server:
    build: 
      context: .
      target: python
    working_dir: /app
    command: python -m server.tls_claude
    volumes:
      - ./server:/app/server
    environment:
      - HOST=0.0.0.0
      - PORT=8000
  client:
    build:
      context: .
      target: python
      args:
        HOSTNAME: go_receiver
    working_dir: /app
    command: python client.py
    volumes:
      - ./client:/app
    environment:
      - HOST=server
      - PORT=8000
    depends_on:
      - server
  rust_client:
    build:
      context: ./rust_client
      dockerfile: ../Dockerfile
      target: rust
      args:
        HOSTNAME: go_receiver
    environment:
      - HOST=receiver
      - PORT=9003
    volumes:
      - ./certs/server.crt:/certs/cert.pem
  receiver:
    build: 
      context: .
      target: receiver
    command: ["python", "-m", "receiver.tls"]
    environment:
      - HOST=0.0.0.0
      - PORT=9003
    ports:
      - "9003:9003/tcp"
    volumes:
      - ./certs:/certs
  go_receiver:
    build:
      context: .
      target: go_receiver
      args:
        HOSTNAME: go_receiver
    environment:
      - HOST=0.0.0.0
      - PORT=9003
    ports:
      - "9003:9003/tcp"
    # volumes:
    #   - ./certs:/certs
