services:
  server:
    build: 
      context: .
      target: python
    working_dir: /app
    command: python -m server.tls
    volumes:
      - ./server:/app/server
    environment:
      - HOST=0.0.0.0
      - PORT=8000
  client:
    build:
      context: .
      target: python
    working_dir: /app
    command: python client.py
    volumes:
      - ./client:/app
    environment:
      - HOST=server
      - PORT=8000
    depends_on:
      - server
  rust_client:
    build:
      context: ./rust_client
      dockerfile: ../Dockerfile
      target: rust
    environment:
      - HOST=server
      - PORT=8000
