services:
  server:
    build: .
    working_dir: /app
    command: python server.py
    volumes:
      - ./server:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
  client:
    build: .
    working_dir: /app
    command: python client.py
    volumes:
      - ./client:/app
    environment:
      - HOST=server
      - PORT=8000
  rust_client:
    build:
      context: ./rust_client
    environment:
      - HOST=server
      - PORT=8000
